CREATE SEQUENCE IF NOT EXISTS "seq_post_id"
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 202700
NOCACHE
NOCYCLE;

CREATE SEQUENCE IF NOT EXISTS "seq_comment_id"
MINVALUE 1
MAXVALUE 999999999
INCREMENT BY 1
START WITH 202700
NOCACHE
NOCYCLE;

CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY,
    title VARCHAR(400) NOT NULL,
    text TEXT NOT NULL,
    tags VARCHAR(400) NOT NULL,
    likesCount INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS comments (
    id INTEGER PRIMARY KEY,
	post_id INTEGER REFERENCES posts ON DELETE CASCADE,
    text VARCHAR(400) NOT NULL
);